version: "3"
services:
  nodejs-1:
    image: node:alpine
    volumes:
      - ./app/:/app
    working_dir: /app
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    networks: 
      - minha-rede
  nodejs-2:
    image: node:alpine
    volumes:
      - ./app/:/app
    working_dir: /app
    environment:
      PORT: 3001
    ports:
      - "3001:3001"
    command: sh -c "npm install && npm start"
    networks: 
      - minha-rede
  nodejs-3:
    image: node:alpine
    volumes:
      - ./app/:/app
    working_dir: /app
    environment:
      PORT: 3002
    ports:
      - "3002:3002"
    command: sh -c "npm install && npm start"
    networks: 
      - minha-rede
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs-1
      - nodejs-2
      - nodejs-3
    networks: 
      - minha-rede
    restart: always 

networks:
  minha-rede:

